// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: log.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppVersion    string                 `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	ContainerId   string                 `protobuf:"bytes,4,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName string                 `protobuf:"bytes,5,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Service       string                 `protobuf:"bytes,7,opt,name=service,proto3" json:"service,omitempty"`
	EventId       string                 `protobuf:"bytes,8,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	User          string                 `protobuf:"bytes,9,opt,name=user,proto3" json:"user,omitempty"`
	Executable    string                 `protobuf:"bytes,10,opt,name=executable,proto3" json:"executable,omitempty"`
	Path          string                 `protobuf:"bytes,11,opt,name=path,proto3" json:"path,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,12,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMeta) Reset() {
	*x = LogMeta{}
	mi := &file_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMeta) ProtoMessage() {}

func (x *LogMeta) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMeta.ProtoReflect.Descriptor instead.
func (*LogMeta) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogMeta) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *LogMeta) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *LogMeta) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *LogMeta) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *LogMeta) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *LogMeta) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *LogMeta) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogMeta) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *LogMeta) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *LogMeta) GetExecutable() string {
	if x != nil {
		return x.Executable
	}
	return ""
}

func (x *LogMeta) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LogMeta) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Pid           int32                  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          map[string]string      `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Meta          *LogMeta               `protobuf:"bytes,9,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *LogEntry) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *LogEntry) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *LogEntry) GetMeta() *LogMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type LogPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	EndpointId    string                 `protobuf:"bytes,4,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Logs          []*LogEntry            `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
	Meta          *Meta                  `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogPayload) Reset() {
	*x = LogPayload{}
	mi := &file_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogPayload) ProtoMessage() {}

func (x *LogPayload) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogPayload.ProtoReflect.Descriptor instead.
func (*LogPayload) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{2}
}

func (x *LogPayload) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LogPayload) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *LogPayload) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *LogPayload) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *LogPayload) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogPayload) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *LogPayload) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{3}
}

func (x *LogResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LogResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_log_proto protoreflect.FileDescriptor

const file_log_proto_rawDesc = "" +
	"\n" +
	"\tlog.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"meta.proto\"\xa7\x03\n" +
	"\aLogMeta\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x1f\n" +
	"\vapp_version\x18\x03 \x01(\tR\n" +
	"appVersion\x12!\n" +
	"\fcontainer_id\x18\x04 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x05 \x01(\tR\rcontainerName\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12\x18\n" +
	"\aservice\x18\a \x01(\tR\aservice\x12\x19\n" +
	"\bevent_id\x18\b \x01(\tR\aeventId\x12\x12\n" +
	"\x04user\x18\t \x01(\tR\x04user\x12\x1e\n" +
	"\n" +
	"executable\x18\n" +
	" \x01(\tR\n" +
	"executable\x12\x12\n" +
	"\x04path\x18\v \x01(\tR\x04path\x12/\n" +
	"\x05extra\x18\f \x03(\v2\x19.proto.LogMeta.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x03\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x05R\x03pid\x123\n" +
	"\x06fields\x18\a \x03(\v2\x1b.proto.LogEntry.FieldsEntryR\x06fields\x12-\n" +
	"\x04tags\x18\b \x03(\v2\x19.proto.LogEntry.TagsEntryR\x04tags\x12\"\n" +
	"\x04meta\x18\t \x01(\v2\x0e.proto.LogMetaR\x04meta\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfd\x01\n" +
	"\n" +
	"LogPayload\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1f\n" +
	"\vendpoint_id\x18\x04 \x01(\tR\n" +
	"endpointId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\x04logs\x18\x06 \x03(\v2\x0f.proto.LogEntryR\x04logs\x12\x1f\n" +
	"\x04meta\x18\a \x01(\v2\v.proto.MetaR\x04meta\"F\n" +
	"\vLogResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode2}\n" +
	"\n" +
	"LogService\x126\n" +
	"\rSubmitMetrics\x12\x11.proto.LogPayload\x1a\x12.proto.LogResponse\x127\n" +
	"\fSubmitStream\x12\x11.proto.LogPayload\x1a\x12.proto.LogResponse(\x01B.Z,github.com/devpospicha/ishared/protob\x06proto3"

var (
	file_log_proto_rawDescOnce sync.Once
	file_log_proto_rawDescData []byte
)

func file_log_proto_rawDescGZIP() []byte {
	file_log_proto_rawDescOnce.Do(func() {
		file_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_log_proto_rawDesc), len(file_log_proto_rawDesc)))
	})
	return file_log_proto_rawDescData
}

var file_log_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_log_proto_goTypes = []any{
	(*LogMeta)(nil),               // 0: proto.LogMeta
	(*LogEntry)(nil),              // 1: proto.LogEntry
	(*LogPayload)(nil),            // 2: proto.LogPayload
	(*LogResponse)(nil),           // 3: proto.LogResponse
	nil,                           // 4: proto.LogMeta.ExtraEntry
	nil,                           // 5: proto.LogEntry.FieldsEntry
	nil,                           // 6: proto.LogEntry.TagsEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*Meta)(nil),                  // 8: proto.Meta
}
var file_log_proto_depIdxs = []int32{
	4,  // 0: proto.LogMeta.extra:type_name -> proto.LogMeta.ExtraEntry
	7,  // 1: proto.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 2: proto.LogEntry.fields:type_name -> proto.LogEntry.FieldsEntry
	6,  // 3: proto.LogEntry.tags:type_name -> proto.LogEntry.TagsEntry
	0,  // 4: proto.LogEntry.meta:type_name -> proto.LogMeta
	7,  // 5: proto.LogPayload.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 6: proto.LogPayload.logs:type_name -> proto.LogEntry
	8,  // 7: proto.LogPayload.meta:type_name -> proto.Meta
	2,  // 8: proto.LogService.SubmitMetrics:input_type -> proto.LogPayload
	2,  // 9: proto.LogService.SubmitStream:input_type -> proto.LogPayload
	3,  // 10: proto.LogService.SubmitMetrics:output_type -> proto.LogResponse
	3,  // 11: proto.LogService.SubmitStream:output_type -> proto.LogResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_log_proto_init() }
func file_log_proto_init() {
	if File_log_proto != nil {
		return
	}
	file_meta_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_log_proto_rawDesc), len(file_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_proto_goTypes,
		DependencyIndexes: file_log_proto_depIdxs,
		MessageInfos:      file_log_proto_msgTypes,
	}.Build()
	File_log_proto = out.File
	file_log_proto_goTypes = nil
	file_log_proto_depIdxs = nil
}
