// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: metric.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatisticValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Minimum       float64                `protobuf:"fixed64,1,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum       float64                `protobuf:"fixed64,2,opt,name=maximum,proto3" json:"maximum,omitempty"`
	SampleCount   int32                  `protobuf:"varint,3,opt,name=sample_count,json=sampleCount,proto3" json:"sample_count,omitempty"`
	Sum           float64                `protobuf:"fixed64,4,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticValues) Reset() {
	*x = StatisticValues{}
	mi := &file_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticValues) ProtoMessage() {}

func (x *StatisticValues) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticValues.ProtoReflect.Descriptor instead.
func (*StatisticValues) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{0}
}

func (x *StatisticValues) GetMinimum() float64 {
	if x != nil {
		return x.Minimum
	}
	return 0
}

func (x *StatisticValues) GetMaximum() float64 {
	if x != nil {
		return x.Maximum
	}
	return 0
}

func (x *StatisticValues) GetSampleCount() int32 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

func (x *StatisticValues) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type Metric struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Namespace         string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Subnamespace      string                 `protobuf:"bytes,2,opt,name=subnamespace,proto3" json:"subnamespace,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value             float64                `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	StatisticValues   *StatisticValues       `protobuf:"bytes,6,opt,name=statistic_values,json=statisticValues,proto3" json:"statistic_values,omitempty"`
	Unit              string                 `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	Dimensions        map[string]string      `protobuf:"bytes,8,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StorageResolution int32                  `protobuf:"varint,9,opt,name=storage_resolution,json=storageResolution,proto3" json:"storage_resolution,omitempty"`
	Type              string                 `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{1}
}

func (x *Metric) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Metric) GetSubnamespace() string {
	if x != nil {
		return x.Subnamespace
	}
	return ""
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetStatisticValues() *StatisticValues {
	if x != nil {
		return x.StatisticValues
	}
	return nil
}

func (x *Metric) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Metric) GetDimensions() map[string]string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *Metric) GetStorageResolution() int32 {
	if x != nil {
		return x.StorageResolution
	}
	return 0
}

func (x *Metric) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type MetricPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	EndpointId    string                 `protobuf:"bytes,4,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,6,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Meta          *Meta                  `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPayload) Reset() {
	*x = MetricPayload{}
	mi := &file_metric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPayload) ProtoMessage() {}

func (x *MetricPayload) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPayload.ProtoReflect.Descriptor instead.
func (*MetricPayload) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{2}
}

func (x *MetricPayload) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricPayload) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *MetricPayload) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MetricPayload) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *MetricPayload) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricPayload) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *MetricPayload) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_metric_proto protoreflect.FileDescriptor

const file_metric_proto_rawDesc = "" +
	"\n" +
	"\fmetric.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"meta.proto\"z\n" +
	"\x0fStatisticValues\x12\x18\n" +
	"\aminimum\x18\x01 \x01(\x01R\aminimum\x12\x18\n" +
	"\amaximum\x18\x02 \x01(\x01R\amaximum\x12!\n" +
	"\fsample_count\x18\x03 \x01(\x05R\vsampleCount\x12\x10\n" +
	"\x03sum\x18\x04 \x01(\x01R\x03sum\"\xc6\x03\n" +
	"\x06Metric\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\"\n" +
	"\fsubnamespace\x18\x02 \x01(\tR\fsubnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\x12A\n" +
	"\x10statistic_values\x18\x06 \x01(\v2\x16.proto.StatisticValuesR\x0fstatisticValues\x12\x12\n" +
	"\x04unit\x18\a \x01(\tR\x04unit\x12=\n" +
	"\n" +
	"dimensions\x18\b \x03(\v2\x1d.proto.Metric.DimensionsEntryR\n" +
	"dimensions\x12-\n" +
	"\x12storage_resolution\x18\t \x01(\x05R\x11storageResolution\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\tR\x04type\x1a=\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x02\n" +
	"\rMetricPayload\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1f\n" +
	"\vendpoint_id\x18\x04 \x01(\tR\n" +
	"endpointId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\ametrics\x18\x06 \x03(\v2\r.proto.MetricR\ametrics\x12\x1f\n" +
	"\x04meta\x18\a \x01(\v2\v.proto.MetaR\x04metaB.Z,github.com/devpospicha/ishared/protob\x06proto3"

var (
	file_metric_proto_rawDescOnce sync.Once
	file_metric_proto_rawDescData []byte
)

func file_metric_proto_rawDescGZIP() []byte {
	file_metric_proto_rawDescOnce.Do(func() {
		file_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metric_proto_rawDesc), len(file_metric_proto_rawDesc)))
	})
	return file_metric_proto_rawDescData
}

var file_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_metric_proto_goTypes = []any{
	(*StatisticValues)(nil),       // 0: proto.StatisticValues
	(*Metric)(nil),                // 1: proto.Metric
	(*MetricPayload)(nil),         // 2: proto.MetricPayload
	nil,                           // 3: proto.Metric.DimensionsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*Meta)(nil),                  // 5: proto.Meta
}
var file_metric_proto_depIdxs = []int32{
	4, // 0: proto.Metric.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: proto.Metric.statistic_values:type_name -> proto.StatisticValues
	3, // 2: proto.Metric.dimensions:type_name -> proto.Metric.DimensionsEntry
	4, // 3: proto.MetricPayload.timestamp:type_name -> google.protobuf.Timestamp
	1, // 4: proto.MetricPayload.metrics:type_name -> proto.Metric
	5, // 5: proto.MetricPayload.meta:type_name -> proto.Meta
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_metric_proto_init() }
func file_metric_proto_init() {
	if File_metric_proto != nil {
		return
	}
	file_meta_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metric_proto_rawDesc), len(file_metric_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metric_proto_goTypes,
		DependencyIndexes: file_metric_proto_depIdxs,
		MessageInfos:      file_metric_proto_msgTypes,
	}.Build()
	File_metric_proto = out.File
	file_metric_proto_goTypes = nil
	file_metric_proto_depIdxs = nil
}
