// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: process.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          int32                  `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Executable    string                 `protobuf:"bytes,4,opt,name=executable,proto3" json:"executable,omitempty"`
	Cmdline       string                 `protobuf:"bytes,5,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,6,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float64                `protobuf:"fixed64,7,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	Threads       int32                  `protobuf:"varint,8,opt,name=threads,proto3" json:"threads,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessInfo) GetExecutable() string {
	if x != nil {
		return x.Executable
	}
	return ""
}

func (x *ProcessInfo) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *ProcessInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *ProcessInfo) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *ProcessInfo) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ProcessInfo) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ProcessPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	EndpointId    string                 `protobuf:"bytes,4,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Processes     []*ProcessInfo         `protobuf:"bytes,6,rep,name=processes,proto3" json:"processes,omitempty"`
	Meta          *Meta                  `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPayload) Reset() {
	*x = ProcessPayload{}
	mi := &file_process_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPayload) ProtoMessage() {}

func (x *ProcessPayload) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPayload.ProtoReflect.Descriptor instead.
func (*ProcessPayload) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessPayload) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ProcessPayload) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ProcessPayload) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ProcessPayload) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *ProcessPayload) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ProcessPayload) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *ProcessPayload) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_process_proto protoreflect.FileDescriptor

const file_process_proto_rawDesc = "" +
	"\n" +
	"\rprocess.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"meta.proto\"\x83\x03\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\x05R\x04ppid\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1e\n" +
	"\n" +
	"executable\x18\x04 \x01(\tR\n" +
	"executable\x12\x18\n" +
	"\acmdline\x18\x05 \x01(\tR\acmdline\x12\x1f\n" +
	"\vcpu_percent\x18\x06 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\a \x01(\x01R\n" +
	"memPercent\x12\x18\n" +
	"\athreads\x18\b \x01(\x05R\athreads\x129\n" +
	"\n" +
	"start_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x120\n" +
	"\x04tags\x18\n" +
	" \x03(\v2\x1c.proto.ProcessInfo.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x02\n" +
	"\x0eProcessPayload\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1f\n" +
	"\vendpoint_id\x18\x04 \x01(\tR\n" +
	"endpointId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x120\n" +
	"\tprocesses\x18\x06 \x03(\v2\x12.proto.ProcessInfoR\tprocesses\x12\x1f\n" +
	"\x04meta\x18\a \x01(\v2\v.proto.MetaR\x04metaB.Z,github.com/devpospicha/ishared/protob\x06proto3"

var (
	file_process_proto_rawDescOnce sync.Once
	file_process_proto_rawDescData []byte
)

func file_process_proto_rawDescGZIP() []byte {
	file_process_proto_rawDescOnce.Do(func() {
		file_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_process_proto_rawDesc), len(file_process_proto_rawDesc)))
	})
	return file_process_proto_rawDescData
}

var file_process_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_process_proto_goTypes = []any{
	(*ProcessInfo)(nil),           // 0: proto.ProcessInfo
	(*ProcessPayload)(nil),        // 1: proto.ProcessPayload
	nil,                           // 2: proto.ProcessInfo.TagsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*Meta)(nil),                  // 4: proto.Meta
}
var file_process_proto_depIdxs = []int32{
	3, // 0: proto.ProcessInfo.start_time:type_name -> google.protobuf.Timestamp
	2, // 1: proto.ProcessInfo.tags:type_name -> proto.ProcessInfo.TagsEntry
	3, // 2: proto.ProcessPayload.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: proto.ProcessPayload.processes:type_name -> proto.ProcessInfo
	4, // 4: proto.ProcessPayload.meta:type_name -> proto.Meta
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_process_proto_init() }
func file_process_proto_init() {
	if File_process_proto != nil {
		return
	}
	file_meta_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_process_proto_rawDesc), len(file_process_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_process_proto_goTypes,
		DependencyIndexes: file_process_proto_depIdxs,
		MessageInfos:      file_process_proto_msgTypes,
	}.Build()
	File_process_proto = out.File
	file_process_proto_goTypes = nil
	file_process_proto_depIdxs = nil
}
